# Generated by Django 5.1.4 on 2025-01-04 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='mar',
            new_name='ativo',
        ),
    ]
