# Generated by Django 5.1.4 on 2025-01-03 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medico', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=2)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('altura', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medico.data')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
